### DISCUSSION TITLE
2022/04/17/hexo-blog-1/

### DISCUSSION THREAD

**Discussion by giscus** [argvchs/giscus-comments#10] [Announcements]
# 2022/04/17/hexo-blog-1/

https://argvchs.github.io/2022/04/17/hexo-blog-1/

**Comment by IamQhe** [comment]
感谢大佬分享，已经跟着教程成功搭建好了[鲜花]

**Comment by Revethere** [comment]
ParticleX 主题怎样支持多个 tag

**Reply by argvchs** [reply]
```yaml
tags: [tag1, tag2]
# or
tags:
    - tag1
    - tag2
```
